import type { Metadata } from "next";
import { inter } from '../app/utilities/fonts'
import Header from "./components/static/Header";
import Footer from "./components/static/Footer";

export const metadata: Metadata = {
  title: "Dynamite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
       <Header />
        {children}
      <Footer />
      </body>
    </html>
);

}
