import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/static/Header";
import Footer from "../components/static/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SyncFusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
       <Header />
        {children}
      <Footer />
      </body>
    </html>
);

}
